### ISSUE TITLE
Contribuições

### ISSUE THREAD

**Issue by rn4n** [marciellioliveira/Navegador#1]
Olá, sou aluno da Fatec também.
Está aceitando contribuições nesse projeto ou é algum tipo de trabalho de semestre?

_cheers_.

**Comment by marciellioliveira** [comment]
Oi, ah legal. ;)
Então, eu estou fazendo esse navegador só pra aprender mesmo...Pra voltar pro semestre que vem um pouco mais preparada. haha 

_cheers_
